GET http://localhost:8000/internship/enterprise
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
GET http://localhost:8000/internship/enterprise/5
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
GET http://localhost:8000/internship/enterprise/partner
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
GET http://localhost:8000/internship/enterprise/potential
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
GET http://localhost:8000/internship/enterprise/potential
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
POST http://localhost:8000/internship/enterprise/
Content-Type: application/json
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

{
    "name":"Gainde 2000",
    "field":"Informatique Telecom",
    "email":"hgainde@gainde.com",
    "website":"http://gainde2000.com/",
    "address":"Mermoz-Pyrotechnie Lot 46 DAKAR.BP 16 482 Dakar-Fann Dakar, Rep du Sénégal",
    "phone":" 338259687",
    "leader_name":"Le con",
    "is_partner" : true
}
###

PUT  http://localhost:8000/internship/enterprise/2/
Content-Type: application/json
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

{
    "name":"Gainde 2000",
    "field":"Informatique Telecom",
    "email":"hgainde@gainde.com",
    "website":"http://gainde2000.com/",
    "address":"Mermoz-Pyrotechnie Lot 46 DAKAR.BP 16 482 Dakar-Fann Dakar, Rep du Sénégal",
    "phone":" 338259687",
    "leader_name":"Le con",
    "is_partner" : true,
    "students":[5 ,6]
}

### 
DELETE http://localhost:8000/internship/enterprise/4/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###

POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"guisse",
    "email":"guisse@gmail.fr",
    "password":"kmtc44",
    "status":"teacher",
    "firstname":"Guisee",
    "lastname":"Abdou",
    "department":"GIT",
    "phone": "774304543"
}
### 

POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"modou1",
    "email":"modou1@gmail.com",
    "password":"kmtc44",
    "status":"student",
    "firstname":"mor",
    "lastname":"kaire",
    "phone":"773444534",
    "department":"GIT",
    "classe":"DIC3",
    "promotion":"44",
    "birthday":"1996-08-08"
}

###
POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"seck",
    "email":"seck@gmail.fr",
    "password":"kmtc44",
    "status":"framer",
    "firstname":"lamine",
    "lastname":"seck",
    "phone":"773444534",
    "enterprise":"1"
}
### 
POST  http://localhost:8000/auth/login
Content-Type: application/json 

{
    "username":"kairemo",
    "password":"kmtc44"
}
###

GET http://localhost:8000/auth/users
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###

GET http://localhost:8000/auth/user
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###

POST http://localhost:8000/auth/logout
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###

GET http://localhost:8000/students
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
PUT http://localhost:8000/students/12/
Content-Type: application/json
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

{
    "username":"kairere",
    "email":"kaire@gmails.fr",
    "password":"kmtc44",
    "status":"student",
    "firstname":"mor",
    "lastname":"kaire",
    "phone":"773444534",
    "department":"GIT",
    "classe":"DIC1",
    "promotion":"1",
    "enterprise":"2"
}

###

GET http://localhost:8000/teachers
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###

GET http://localhost:8000/framers
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###

GET http://localhost:8000/promos
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
POST http://localhost:8000/promos
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
Content-Type: application/json

{
    "name":"43"
}
###
GET http://localhost:8000/department
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###
GET http://localhost:8000/classroom/1
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
###
POST http://localhost:8000/department
Content-Type: application/json
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

{
    "name": "GC"
}
###
POST http://localhost:8000/classroom
Content-Type: application/json
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

{
    "name": "DIC1"
}
###

GET http://localhost:8000/internship/convention
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###

DELETE  http://localhost:8000/internship/convention/6/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
POST http://localhost:8000/internship/convention/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
Content-Type: application/json

{
    "title":"Partenariat avec Sonatel",
    "enterprise":"2",
    "life_time": "3",
    "state":"R"
}
###
GET http://localhost:8000/task/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###

GET http://localhost:8000/project/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5

###
PUT http://localhost:8000/project/1/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
Content-Type: application/json

{
    "title":"Realisation d'un chatbot",
    "description":"/un chatbot permettant a un ecolier d'apprendre ces lecons",
    "aim": "Faciliter au jeune l'acces au connaissance",
    "enterprise":"2",
    "framer":"1",
    "students":[1,2,3]
}
###

POST http://localhost:8000/task/
Authorization: Token c55a80569d7478ef4db92dd32cb16644dab7b47a1660168450e587a5c386eea5
Content-Type: application/json

{
    "title":"Apprendre dialog fuel",
    "description":"Allez dans le lien de la tache et apprendre la techmologie pour relaliser une chatbot",
    "enterprise":"2",
    "framer":"1",
    "students":["1"],
    "project": "1"
}
###
