GET http://localhost:8000/internship/enterprise
Authorization: Token 3647eb869c57a900db44bb8761f02b3da37d3fc777db2126869f5dff587cb1a3

###
GET http://localhost:8000/internship/enterprise/1

###

POST http://localhost:8000/internship/enterprise/
Content-Type: application/json
Authorization: Token 2b178b257b45d4c42d876c8a12037ba59be74b92af9fc8cc2130516cfd9065cb

{
    "name":"Getrans",
    "field":"Genie Civil",
    "email":"getran@getran.com",
    "website":"http://groupegetran.com/",
    "address":"Mermoz-Pyrotechnie Lot 46 DAKAR.BP 16 482 Dakar-Fann Dakar, Rep du Sénégal",
    "phone":" 338259687",
    "leader_name":"Mar Thiam "
}

### 
DELETE http://localhost:8000/internship/enterprise/4/
Authorization: Token 3647eb869c57a900db44bb8761f02b3da37d3fc777db2126869f5dff587cb1a3
###

POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"guisse1",
    "email":"guisse@gnmail.fr",
    "password":"kmtc44",
    "status":"teacher",
    "firstname":"Guisee",
    "lastname":"Abdou",
    "department":"GIT",
    "phone": "774304543"
}
### 

POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"kaire32",
    "email":"morkaa@kaire.fr",
    "password":"kmtc44",
    "status":"student",
    "promotion":"44",
    "firstname":"mor",
    "lastname":"kaire",
    "phone" : "775434323",
    "department":"GIT",
    "classe":"DIC1"
}
### 

POST  http://localhost:8000/auth/register
Content-Type: application/json 

{
    "username":"secka",
    "email":"seck@kaire.fr",
    "password":"kmtc44",
    "status":"framer",
    "firstname":"lamine",
    "lastname":"seck",
    "phone":"773444534"
}
### 
POST  http://localhost:8000/auth/login
Content-Type: application/json 

{
    "username":"kairemor",
    "password":"kmtc"
}
###

GET http://localhost:8000/auth/users
Authorization: Token 7cb4b3f5d1be5703fb83585d882491dba931b71f96327629c52492975b69030c
###

GET http://localhost:8000/auth/user
Authorization: Token 7cb4b3f5d1be5703fb83585d882491dba931b71f96327629c52492975b69030c
###

POST http://localhost:8000/auth/logout
Authorization: Token 3647eb869c57a900db44bb8761f02b3da37d3fc777db2126869f5dff587cb1a3
###

GET http://localhost:8000/students
Authorization: Token c46b71e4ae395b7825889a49b731a644fc05d331b99bc9a3acb47c640e2ee346

###

GET http://localhost:8000/teachers
Authorization: Token c46b71e4ae395b7825889a49b731a644fc05d331b99bc9a3acb47c640e2ee346

###

GET http://localhost:8000/framers
Authorization: Token c46b71e4ae395b7825889a49b731a644fc05d331b99bc9a3acb47c640e2ee346

###

GET http://localhost:8000/promos
Authorization: Token c46b71e4ae395b7825889a49b731a644fc05d331b99bc9a3acb47c640e2ee346

###